### ISSUE TITLE
Internal ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by CedrickFlocon** [deezer/android-sample#2]
I don't see any sdk repository, so i put my issue (not a disaster :)) in this sample repository.

_com.deezer.sdk.player.AbstractTrackListPlayer#getCurrentTrack()_ throw an _ArrayIndexOutOfBoundsException_ if _com.deezer.sdk.player.AbstractTrackListPlayer#getTracks().size() == 0_.

You should probably send null ?

By the way this sdk is realy easy to use :+1:
Thanks

**Comment by xgouchet** [comment]
Hi Cedrick, 

thanx for this update, I'll take a look into it asap.
